### ISSUE TITLE
`0` should be an allowed node

### ISSUE THREAD

**Issue by peoro** [pauldijou/armillary#1]
Hello!

I tried to use this library, but found an issue.

I'm using integers ranging from `0` to `width*height-1` to represent nodes in my graph, but if I pass `0` as either the starting or ending node of `armillary.aStar` I get an error.

I believe that if you want the check on the existence of `start` or `end`, you should check whether the variable is undefined.

**Comment by pauldijou** [comment]
Fixed in 0.1.3
